jobs:
  badge:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.4']
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: docker-compose up
        run: docker-compose up
        env:
          PHP_VERSION: ${{ matrix.php }}
          INFECTION_BADGE_API_KEY: ${{secrets.INFECTION_BADGE_API_KEY}}
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master